2025-05-26 12:53 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 132, in try_moving_active_card
    if self.active_card_pile.is_last_card(self.active_card) or self.active_card_pile.is_a_stock_pile():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 27, in is_last_card
    return card == self.card_list[-1]
                   ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 12:53 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 132, in try_moving_active_card
    if self.active_card_pile.is_last_card(self.active_card) or self.active_card_pile.is_a_stock_pile():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 27, in is_last_card
    return card == self.card_list[-1]
                   ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 12:53 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 132, in try_moving_active_card
    if self.active_card_pile.is_last_card(self.active_card) or self.active_card_pile.is_a_stock_pile():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 27, in is_last_card
    return card == self.card_list[-1]
                   ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 12:53 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 132, in try_moving_active_card
    if self.active_card_pile.is_last_card(self.active_card) or self.active_card_pile.is_a_stock_pile():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 27, in is_last_card
    return card == self.card_list[-1]
                   ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 12:53 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 132, in try_moving_active_card
    if self.active_card_pile.is_last_card(self.active_card) or self.active_card_pile.is_a_stock_pile():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 27, in is_last_card
    return card == self.card_list[-1]
                   ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 12:53 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 132, in try_moving_active_card
    if self.active_card_pile.is_last_card(self.active_card) or self.active_card_pile.is_a_stock_pile():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 27, in is_last_card
    return card == self.card_list[-1]
                   ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 12:53 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 132, in try_moving_active_card
    if self.active_card_pile.is_last_card(self.active_card) or self.active_card_pile.is_a_stock_pile():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 27, in is_last_card
    return card == self.card_list[-1]
                   ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 12:57 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 133, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 79, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 12:57 - ERROR: 'StockPile' object has no attribute 'return_next_cards'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 140, in try_moving_active_card
    cards = self.active_card_pile.return_next_cards(self.active_card)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StockPile' object has no attribute 'return_next_cards'
2025-05-26 12:57 - ERROR: 'StockPile' object has no attribute 'return_next_cards'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 140, in try_moving_active_card
    cards = self.active_card_pile.return_next_cards(self.active_card)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StockPile' object has no attribute 'return_next_cards'
2025-05-26 13:21 - ERROR: 'str' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 132, in try_moving_active_card
    if self.active_card_pile.is_last_card(self.active_card) or self.active_card.return_pile() == 'STOCK':
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 208, in return_pile
    return self.pile.name
           ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'
2025-05-26 13:21 - ERROR: 'str' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 132, in try_moving_active_card
    if self.active_card_pile.is_last_card(self.active_card) or self.active_card.return_pile() == 'STOCK':
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 208, in return_pile
    return self.pile.name
           ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'
2025-05-26 13:21 - ERROR: 'str' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 132, in try_moving_active_card
    if self.active_card_pile.is_last_card(self.active_card) or self.active_card.return_pile() == 'STOCK':
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 208, in return_pile
    return self.pile.name
           ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'
2025-05-26 13:23 - ERROR: 'StockPile' object has no attribute 'return_next_cards'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 140, in try_moving_active_card
    cards = self.active_card_pile.return_next_cards(self.active_card)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StockPile' object has no attribute 'return_next_cards'
2025-05-26 13:24 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 133, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 13:24 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 133, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 13:25 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 133, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 13:25 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 133, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 13:25 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 133, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 13:25 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 114, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 13:26 - ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 141, in try_moving_active_card
    for count, card in enumerate(cards):
                       ~~~~~~~~~^^^^^^^
TypeError: 'NoneType' object is not iterable
2025-05-26 13:26 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 114, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 13:31 - ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 141, in try_moving_active_card
    for count, card in enumerate(cards):
                       ~~~~~~~~~^^^^^^^
TypeError: 'NoneType' object is not iterable
2025-05-26 13:36 - ERROR: bad operand type for abs(): 'enumerate'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 141, in try_moving_active_card
    for count, card in -abs(enumerate(cards)):
                        ~~~^^^^^^^^^^^^^^^^^^
TypeError: bad operand type for abs(): 'enumerate'
2025-05-26 13:36 - ERROR: bad operand type for abs(): 'enumerate'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 141, in try_moving_active_card
    for count, card in -abs(enumerate(cards)):
                        ~~~^^^^^^^^^^^^^^^^^^
TypeError: bad operand type for abs(): 'enumerate'
2025-05-26 13:36 - ERROR: bad operand type for abs(): 'enumerate'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 141, in try_moving_active_card
    for count, card in -abs(enumerate(cards)):
                        ~~~^^^^^^^^^^^^^^^^^^
TypeError: bad operand type for abs(): 'enumerate'
2025-05-26 13:36 - ERROR: bad operand type for abs(): 'enumerate'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 141, in try_moving_active_card
    for count, card in -abs(enumerate(cards)):
                        ~~~^^^^^^^^^^^^^^^^^^
TypeError: bad operand type for abs(): 'enumerate'
2025-05-26 13:36 - ERROR: bad operand type for abs(): 'enumerate'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 141, in try_moving_active_card
    for count, card in -abs(enumerate(cards)):
                        ~~~^^^^^^^^^^^^^^^^^^
TypeError: bad operand type for abs(): 'enumerate'
2025-05-26 13:37 - ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 141, in try_moving_active_card
    for count, card in enumerate(cards):
                       ~~~~~~~~~^^^^^^^
TypeError: 'NoneType' object is not iterable
2025-05-26 13:37 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 114, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 13:39 - ERROR: 'StockPile' object has no attribute 'return_next_cards'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 140, in try_moving_active_card
    cards = self.active_card_pile.return_next_cards(self.active_card)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StockPile' object has no attribute 'return_next_cards'
2025-05-26 13:46 - ERROR: list.remove(x): x not in list
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 145, in try_moving_active_card
    self.active_card_pile.card_list.remove(card)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
ValueError: list.remove(x): x not in list
2025-05-26 13:52 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 114, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 13:52 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 133, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 13:52 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 133, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 14:01 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 133, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 14:03 - ERROR: 'StockPile' object has no attribute 'return_next_cards'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 140, in try_moving_active_card
    cards = self.active_card_pile.return_next_cards(self.active_card)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StockPile' object has no attribute 'return_next_cards'
2025-05-26 14:04 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 130, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 14:04 - ERROR: 'StockPile' object has no attribute 'return_next_cards'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 140, in try_moving_active_card
    cards = self.active_card_pile.return_next_cards(self.active_card)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StockPile' object has no attribute 'return_next_cards'
2025-05-26 14:04 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 133, in try_moving_active_card
    self.active_card_pile.move_to()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 83, in move_to
    self.turned_card_list[-1].turn()
    ~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-26 14:09 - ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 96, in game
    desk.on_click(mouse_x, mouse_y)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 82, in on_click
    if self.try_moving_active_card():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/desk.py", line 141, in try_moving_active_card
    for count, card in enumerate(cards):
                       ~~~~~~~~~^^^^^^^
TypeError: 'NoneType' object is not iterable
